apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik 
  namespace: argocd
spec:
  project: argo-project
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: 10.24.3 
    chart: traefik 
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: installCRDs
          value: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik 
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
