values: |
  commonLabels: { "team_name": "morgoth" }
  targetSystem: "linux"
  datadog:
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret
    clusterName: "morgoth"
    tags: ["env:vultr", "newtag:something"]
    kubelet:
      tlsVerify:  false
    logLevel: INFO
    processAgent:
      enabled: true
      processCollection: true
    networkMonitoring:
      enabled: true
    podLabelsAsTags:
      app: kube_app
      release: helm_release
