argo-cd:
  logLevel: debug
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argocd
          url: https://argoproj.github.io/argo-helm
