apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: datadog 
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/jtmack6/argo-infra.git
      revision: HEAD
      files:
      - path: "argocd/datadog/**.yaml"
  project: argo-project
  source:
    repoURL: https://helm.datadoghq.com
    targetRevision: 3.1.2
    chart: datadog 
    helm:
      values: |
        targetSystem: "linux"
        datadog:
          apiKeyExistingSecret: datadog-secret
          appKeyExistingSecret: datadog-secret
          clusterName: "morgoth"
          kubelet:
            tlsVerify:  false
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: datadog 
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
